### ISSUE TITLE
how to copy/yank node text to clipboard?

### ISSUE THREAD

**Issue by HarshilPatel007** [s1n7ax/youtube-neovim-treesitter-query#2]
Hi @s1n7ax ,
I'm new to lua and neovim I saw your videos (and looking forward to see part two of javadoc tutorial and more like that tutorials in future)
My question is how can I copy node text that I'm getting to clipboard?
example:
here we got/printed methods/functions name. now how can I copy them to clipboard instead of printing them?
https://github.com/s1n7ax/youtube-neovim-treesitter-query/blob/de6511ec45f10096207f8a9c12799f2f98033706/run.lua#L22

**Comment by s1n7ax** [comment]
```lua
local a = 'hello world'
vim.cmd(string.format('let @+ = "%s"', a))
```

"+" is the registry. This works on neovim.

**Comment by HarshilPatel007** [comment]
> vim.cmd(string.format('let @+ = "%s"', a))

getting error:
`clipboard: error invoking wl-copy`

edit/update:
working but,  it only copy last entries from list.

I've list of python methods printing like this,
method1()
method2()
method3()
method4()

but, when I've use your solution, I'm getting method4() only.

my code:
```lua
    for _, matches, _ in query:iter_matches(cls_node, 0) do -- id, matches, metadata
        local get_fields = vim.treesitter.query.get_node_text(matches[1], 0)
        vim.cmd(string.format('let @+ = "%s"', get_fields))
    end
```

**Comment by s1n7ax** [comment]
```lua
local t = {}

for _, matches, _ in query:iter_matches(cls_node, 0) do -- id, matches, metadata
    local get_fields = vim.treesitter.query.get_node_text(matches[1], 0)
    table.insert(t, get_fields)
end

vim.cmd(string.format('let @+ = "%s"', table.concat(t, ", ")))
```

**Comment by HarshilPatel007** [comment]
@s1n7ax , thanks a lot bro.
I've tried that things from bit of googling. But, the problem is that I was creating those tables inside the for loop. 😀
I'm fairly new to lua.
Your tutorials helped a lot.
Still waiting for the second part of docstring tutorial and more such tutorials. This tutorials helping a lot to new lua programmers and Neovim users like me.
